services:
  app:
    container_name: samambaia-menu
    image: node:latest
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: >
      bash -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development